let data = [
	{
		id : 1,
		isbn : "9788490325070",
		author : "George Orwell",
		category : "RECOMENDADO",
		country : "Inglaterra",
		description : "1984 de George Orwell, es una distopía que se desarrolla en un futuro totalitario en el que el Estado controla todos los aspectos de la vida de los ciudadanos. El protagonista, Winston Smith, trabaja en el Ministerio de la Verdad, donde manipulan la historia para favorecer al régimen. Winston se rebela contra el sistema, inicia una relación prohibida y comienza a cuestionar la realidad impuesta por el Partido.",
		editorial : "Debolsillo",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/1.png?alt=media&token=c9e26ef1-7d17-4c6d-80e9-8566e7a36b7b&_gl=1*4pshcq*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNTU3NC4yMi4wLjA.",
		price : 5990,
		priceOff : 5690,
		subgenre : "Ciencia Ficción",
		title : "1984",
		type : "Ebook",
		year : "1949"
	},
	{
		id : 2,
		isbn : "9788415618713",
		author : "Lewis Carroll",
		category : "FANTASÍA",
		country : "Inglaterra",
		description : "Alicia en el País de las Maravillas es una obra clásica de Lewis Carroll que narra la historia de Alicia, una niña curiosa que cae por un agujero y entra en un mundo fantástico lleno de criaturas peculiares y situaciones absurdas. Allí, se encuentra con el Conejo Blanco, el Gato de Cheshire, el Sombrerero Loco y la Reina de Corazones. A lo largo de su viaje, Alicia enfrenta desafíos lógicos y físicos ilógicos que desafían la realidad, mientras lucha por encontrar su camino de regreso a casa.",
		editorial : "Alma Europa",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/2.png?alt=media&token=f76d74a8-d180-402c-92f3-0856dc36d0ce&_gl=1*etiw77*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNTY5NS4yNS4wLjA.",
		price : 9950,
		priceOff : 9452,
		subgenre : "Infantil",
		title : "Alicia en el País de las Maravillas",
		type : "Tapa Blanda",
		year : "1865"
	},
	{
		id : 3,
		isbn : "9788467049480",
		author : "Lev Tolstói",
		category : "CLÁSICO",
		country : "Rusia",
		description : "Ana Karenina de Lev Tolstói narra la historia de Ana Karenina, una mujer de alta sociedad en la Rusia del siglo XIX, quien se involucra en un apasionado romance con el conde Vronski, desafiando las normas sociales y su matrimonio con Alexei Karenin. Paralelamente, se sigue la historia de Levin, un terrateniente y filósofo, quien busca la verdad y la felicidad en la vida rural.",
		editorial : "Espasa Libros",
		genre : "Novela",
		language : "Ruso",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/3.png?alt=media&token=638cf7ad-2ceb-4a7b-bdbb-ab2fcc1c825e&_gl=1*odfct3*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNTgwMC41OC4wLjA.",
		price : 16950,
		priceOff : 16102,
		subgenre : "Realista",
		title : "Ana Karenina",
		type : "Tapa Dura",
		year : "1877"
	},
	{
		id : 4,
		isbn : "9788439732471",
		author : "Gabriel García Márquez",
		category : "RECOMENDADO",
		country : "Colombia",
		description : "Cien Años de Soledad de Gabriel García Márquez narra la historia de la familia Buendía a lo largo de siete generaciones en el ficticio pueblo de Macondo, Colombia. La novela mezcla realismo mágico con elementos históricos y mitológicos, creando un mundo lleno de eventos extraordinarios y personajes memorables. La historia explora temas de amor, soledad, poder y decadencia, mientras la familia Buendía enfrenta un ciclo de repetición de errores y tragedias.",
		editorial : "Literatura Random House",
		genre : "Novela",
		language : "Español",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/4.png?alt=media&token=d8794b12-9bd9-4390-a849-2807c9a3e60c&_gl=1*jrsz2*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNTkwNi42MC4wLjA.",
		price : 24900,
		priceOff : 23655,
		subgenre : "Realista",
		title : "Cien Años de Soledad",
		type : "Tapa Dura",
		year : "1967"
	},
	{
		id : 5,
		isbn : "9788466358392",
		author : "E. L. James",
		category : "RECOMENDADO",
		country : "Inglaterra",
		description : "Cincuenta Sombras de Grey de E.L. James es una novela erótica que sigue la relación entre Anastasia Steele, una joven tímida, y Christian Grey, un apuesto empresario con gustos sexuales peculiares. La trama se centra en su complicada relación, que incluye prácticas BDSM. A medida que Ana explora este mundo desconocido, enfrenta desafíos emocionales y psicológicos.",
		editorial : "Debolsillo",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/5.png?alt=media&token=881af56b-479d-454a-9b59-8046c5c6d996&_gl=1*ceknmq*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNjg1MS42MC4wLjA.",
		price : 9950,
		priceOff : 9452,
		subgenre : "Erótica",
		title : "Cincuenta sombras de Grey",
		type : "Tapa Blanda",
		year : "2011"
	},
	{
		id : 6,
		isbn : "9788418008122",
		author : "Fiodor Dostoevskiï",
		category : "NUEVO INGRESO",
		country : "Rusia",
		description : "Crimen y Castigo de Fyodor Dostoevsky sigue la historia de Rodion Raskolnikov, un estudiante pobre en San Petersburgo que comete un asesinato premeditado por razones filosóficas y económicas. A medida que la culpa y la paranoia lo consumen, Raskolnikov se enfrenta a un investigador astuto, Porfiry, y lucha con su propia moralidad. A través del personaje de Raskolnikov, Dostoevsky cuestiona las ideas de la justicia y la moral en la sociedad rusa del siglo XIX.",
		editorial : "Alma Europa",
		genre : "Novela",
		language : "Ruso",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/6.png?alt=media&token=e8dad1d6-78cc-4866-8596-0e0a5907a068&_gl=1*j0303e*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNjg5OS4xMi4wLjA.",
		price : 21950,
		priceOff : 20852,
		subgenre : "Psicológica",
		title : "Crimen y Castigo",
		type : "Tapa Dura",
		year : "1866"
	},
	{
		id : 7,
		isbn : "9788445076538",
		author : "Ray Bradbury",
		category : "NUEVO INGRESO",
		country : "Estados Unidos",
		description : "Crónicas Marcianas de Ray Bradbury es una colección de relatos que exploran la colonización de Marte por parte de la humanidad. Cada historia presenta un aspecto único de la vida en Marte, desde la llegada de los primeros colonizadores hasta la adaptación de los humanos a un nuevo entorno.",
		editorial : "Minotauro",
		genre : "Relatos",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/7.png?alt=media&token=f1a03223-c90f-43fc-8152-b850b19aca83&_gl=1*1fotcug*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNjk4MC40NS4wLjA.",
		price : 9950,
		priceOff : 9452,
		subgenre : "Ciencia Ficción",
		title : "Crónicas Marcianas",
		type : "Tapa Blanda",
		year : "1950"
	},
	{
		id : 8,
		isbn : "9788491813323",
		author : "Emily Brontë",
		category : "CLÁSICO",
		country : "Inglaterra",
		description : "Cumbres Borrascosas de Emily Brontë es una novela gótica que narra la turbulenta historia de amor y venganza entre Heathcliff y Catherine en la sombría mansión de Cumbres Borrascosas en la campiña inglesa. La trama abarca generaciones y explora temas de pasión, obsesión y la destrucción mutua de los personajes principales.",
		editorial : "Alianza Literaria",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/8.png?alt=media&token=79fff206-2402-49d0-b857-d7694ecb8aa6&_gl=1*16b5wmi*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNzE1My42MC4wLjA.",
		price : 22950,
		priceOff : 21802,
		subgenre : "Gótica",
		title : "Cumbres Borrascosas",
		type : "Tapa Blanda",
		year : "1847"
	},
	{
		id : 9,
		isbn : "9788401027277",
		author : "Ana Frank",
		category : "RECOMENDADO",
		country : "Paises Bajos",
		description : "Diario de Ana Frank es el relato íntimo de Ana Frank, una niña judía que se escondió con su familia en un anexo secreto durante la Segunda Guerra Mundial para escapar de la persecución nazi. El diario, escrito durante dos años, refleja los miedos, las esperanzas y las experiencias de Ana mientras lucha por mantener su humanidad en medio de la opresión. La obra es un testimonio conmovedor de la resiliencia y el sufrimiento de los judíos durante el Holocausto. Aunque Ana no sobrevivió, su diario perdura como un recordatorio de la humanidad y la importancia de recordar los horrores del pasado.",
		editorial : "Plaza & Janes Editores",
		genre : "Autobiográfico",
		language : "Neerlandés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/9.png?alt=media&token=ce7d1141-0529-452b-8019-8864db1b60d4&_gl=1*f6dltq*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNzI0My42MC4wLjA.",
		price : 19900,
		priceOff : 18905,
		subgenre : "Diario",
		title : "Diario de Anne Frank",
		type : "Tapa Dura",
		year : "1947"
	},
	{
		id : 10,
		isbn : "9788492966332",
		author : "Agatha Christie",
		category : "MÁS VENDIDO",
		country : "Inglaterra",
		description : "Diez Negritos es una novela de misterio de Agatha Christie en la que diez extraños son invitados a una isla remota por un anfitrión desconocido. A medida que los invitados comienzan a ser asesinados uno por uno, el grupo se da cuenta de que están atrapados en la isla con el asesino entre ellos. La historia se desarrolla como una cuenta regresiva mortal mientras los personajes intentan descubrir quién es el culpable antes de que todos sean eliminados.",
		editorial : "RBA Libros",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/10.png?alt=media&token=79f0f089-78bc-43d2-97b0-d9599517cde7&_gl=1*is479i*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNzMxNC41Mi4wLjA.",
		price : 850,
		priceOff : 807,
		subgenre : "Misterio y/o Suspenso",
		title : "Diez Negritos",
		type : "Ebook",
		year : "1939"
	},
	{
		id : 11,
		isbn : "9788437632186",
		author : "Dante Alighieri",
		category : "NUEVO INGRESO",
		country : "Francia",
		description : "La Divina Comedia es un poema épico de Dante Alighieri que narra el viaje del protagonista, Dante, a través del Infierno, el Purgatorio y el Paraíso. Guiado por Virgilio y Beatriz, Dante encuentra personajes históricos y mitológicos mientras enfrenta castigos y desafíos espirituales. A medida que avanza, busca la redención y la comprensión de la divinidad.",
		editorial : "Catedral",
		genre : "Poema Épico",
		language : "Francés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/11.png?alt=media&token=b5605930-eb5c-4515-9684-836b14ca15b9&_gl=1*81rsun*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNzQ3OS42MC4wLjA.",
		price : 13950,
		priceOff : 13252,
		subgenre : "Epopeya",
		title : "Divina Comedia",
		type : "Tapa Dura",
		year : "1472"
	},
	{
		id : 12,
		isbn : "9788431673963",
		author : "Miguel de Cervantes",
		category : "MÁS VENDIDO",
		country : "España",
		description : "Don Quijote de la Mancha de Miguel de Cervantes narra las aventuras de un hidalgo llamado Don Quijote que enloquece luego de leer demasiados libros de caballerías y decide convertirse en un caballero andante, adoptando el nombre de Don Quijote. Acompañado por su fiel escudero Sancho Panza, se embarca en una serie de locas aventuras por toda España, enfrentando molinos de viento que cree que son gigantes y defendiendo a doncellas en apuros.",
		editorial : "Vicens-Vives",
		genre : "Novela",
		language : "Español",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/12.png?alt=media&token=71490da0-54e3-4392-81e7-0a7bbf80fced&_gl=1*rlae8w*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNzQ5Ny40Mi4wLjA.",
		price : 21750,
		priceOff : 20662,
		subgenre : "Aventuras",
		title : "Don Quijote de la Mancha",
		type : "Tapa Blanda",
		year : "1605"
	},
	{
		id : 13,
		isbn : "9781435159570",
		author : "Bram Stoker",
		category : "FANTASÍA",
		country : "Estados Unidos",
		description : "Drácula de Bram Stoker es una novela gótica que sigue la historia del conde Drácula, un vampiro que se traslada de Transilvania a Inglaterra con el fin de propagar su maldición no muerta. Jonathan Harker, un abogado inglés, es enviado a la mansión de Drácula y descubre su verdadera naturaleza. A medida que Drácula llega a Inglaterra, un grupo de personas, liderado por el profesor Abraham Van Helsing, se une para luchar contra él y salvar a sus víctimas, incluida Mina Harker, esposa de Jonathan.",
		editorial : "Barnes & Noble",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/13.png?alt=media&token=a9ce3b67-3f85-4c6e-8f98-97b446289a43&_gl=1*ysbq09*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNzU3My41MC4wLjA.",
		price : 15000,
		priceOff : 14250,
		subgenre : "Gótica",
		title : "Drácula",
		type : "Tapa Blanda",
		year : "1897"
	},
	{
		id : 14,
		isbn : "9788408144755",
		author : "Paulo Coelho",
		category : "NUEVO INGRESO",
		country : "Brasil",
		description : "El Alquimista de Paulo Coelho cuenta la historia de Santiago, un joven pastor español que sueña con encontrar un tesoro en las pirámides de Egipto. Dejando atrás su vida cómoda, emprende un viaje en busca de su Leyenda Personal. Durante su travesía, Santiago experimenta aventuras, conoce a personajes que le enseñan lecciones de vida y descubre que el verdadero tesoro está en el camino y en el autoconocimiento.",
		editorial : "Planeta",
		genre : "Novela",
		language : "Portugués",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/14.png?alt=media&token=e64541d7-9d46-40bc-b230-a3140d5afdee&_gl=1*14f06wu*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNzY5Ni4xLjAuMA..",
		price : 18000,
		priceOff : 17100,
		subgenre : "Aventuras",
		title : "El Alquimista",
		type : "Tapa Dura",
		year : "1988"
	},
	{
		id : 15,
		isbn : "9788411720151",
		author : "Sun Tzu",
		category : "NUEVO INGRESO",
		country : "China",
		description : "El Arte de la Guerra de Sun Tzu es un antiguo tratado militar chino que ofrece estrategias y tácticas para la guerra y la toma de decisiones en conflictos. El libro enfatiza la importancia de la planificación, la flexibilidad y la sorpresa en la guerra. También se centra en la importancia del conocimiento y la comprensión del enemigo, así como en la necesidad de evitar conflictos innecesarios cuando sea posible.",
		editorial : "Obelisco",
		genre : "Tratado Militar",
		language : "Chino Antiguo",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/15.png?alt=media&token=31b8077c-e85b-4168-ae9c-8aa0d094a475&_gl=1*1omb7wz*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNzc3NC42MC4wLjA.",
		price : 29000,
		priceOff : 27750,
		subgenre : "Militar",
		title : "El Arte de la Guerra",
		type : "Tapa Blanda",
		year : "400 A.C."
	},
	{
		id : 16,
		isbn : "9788408273790",
		author : "Dan Brown",
		category : "RECOMENDADO",
		country : "Estados Unidos",
		description : "El Código Da Vinci es una novela de misterio y suspenso escrita por Dan Brown. La historia sigue al profesor de simbología Robert Langdon mientras investiga el asesinato de un curador del Louvre en París. A medida que avanza la trama, Langdon descubre una serie de pistas y símbolos que apuntan a un antiguo secreto que podría sacudir los fundamentos del cristianismo.",
		editorial : "Planeta",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/16.png?alt=media&token=938fed32-2c40-40ae-a6e8-b33390621af0&_gl=1*12lpvj4*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNzg2Ni42MC4wLjA.",
		price : 7950,
		priceOff : 7552,
		subgenre : "Misterio y/o Suspenso",
		title : "El Código Da Vinci",
		type : "Tapa Blanda",
		year : "2003"
	},
	{
		id : 17,
		isbn : "9788413626710",
		author : "Alexandre Dumas",
		category : "NUEVO INGRESO",
		country : "Francia",
		description : "El Conde de Montecristo es una novela escrita por Alexandre Dumas. La historia sigue a Edmond Dantès, un joven marinero injustamente encarcelado en el siglo XIX. Tras su escape de prisión, Dantès se convierte en el enigmático Conde de Montecristo y busca la venganza contra aquellos que lo traicionaron.",
		editorial : "Alianza Editorial",
		genre : "Novela",
		language : "Francés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/17.png?alt=media&token=cd1919d4-9470-4191-b985-9fefc4082669&_gl=1*1gcfbki*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwNzk0OC40MC4wLjA.",
		price : 16990,
		priceOff : 16140,
		subgenre : "Aventuras",
		title : "El Conde de Montecristo",
		type : "Ebook",
		year : "1844"
	},
	{
		id : 18,
		isbn : "9788466356138",
		author : "Albert Camus",
		category : "NUEVO INGRESO",
		country : "Francia",
		description : "El Extranjero es una novela escrita por Albert Camus. Narra la historia de Meursault, un hombre apático y desconectado de sus emociones. Tras cometer un asesinato aparentemente sin motivo en un acto de indiferencia, es llevado a juicio.",
		editorial : "Debolsillo",
		genre : "Novela",
		language : "Francés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/18.png?alt=media&token=a863aae8-fb9b-4c98-83c8-46c65268986b&_gl=1*pp2mgr*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwODAyOC42MC4wLjA.",
		price : 12950,
		priceOff : 12302,
		subgenre : "Filosófica",
		title : "El Extranjero",
		type : "Tapa Blanda",
		year : "1942"
	},
	{
		id : 19,
		isbn : "9788413621364",
		author : "F. Scott Fitzgerald",
		category : "RECOMENDADO",
		country : "Estados Unidos",
		description : "El Gran Gatsby de F. Scott Fitzgerald es una novela que se desarrolla en la década de 1920 en Nueva York y sigue la vida de Jay Gatsby, un millonario enigmático. El narrador, Nick Carraway, observa la extravagante vida de Gatsby y su obsesión por Daisy Buchanan, su amor de juventud.",
		editorial : "Alianza Editorial",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/19.png?alt=media&token=084225d5-f8b0-42eb-84a4-af531cb91b6b&_gl=1*1frgenp*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUwMTQzMC4xLjEuMTY5NjUwODA0NC40NC4wLjA.",
		price : 12500,
		priceOff : 11875,
		subgenre : "Tragedia",
		title : "El Gran Gatsby",
		type : "Tapa Blanda",
		year : "1925"
	},
	{
		id : 20,
		isbn : "9788491049418",
		author : "J.D. Salinger",
		category : "MÁS VENDIDO",
		country : "Estados Unidos",
		description : "El Guardián Entre el Centeno es una novela escrita por J.D. Salinger. Narra la historia de Holden Caulfield, un joven desencantado que es expulsado de un internado y se embarca en un viaje por Nueva York. A lo largo de sus andanzas, Holden se enfrenta a la hipocresía y la falta de autenticidad en la sociedad adulta, mientras lucha contra su propia confusión y alienación.",
		editorial : "Alianza Editorial",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/20.png?alt=media&token=8f8cd65e-2cdd-4a15-8f5f-002684c14791&_gl=1*1sqzw7j*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNjgwMi40OS4wLjA.",
		price : 16950,
		priceOff : 16102,
		subgenre : "Aprendizaje",
		title : "El Guardián Entre el Centeno",
		type : "Tapa Blanda",
		year : "1951"
	},
	{
		id : 21,
		isbn : "9788445077948",
		author : "J.R.R. Tolkien",
		category : "FANTASÍA",
		country : "Estados Unidos",
		description : "El Hobbit es una novela escrita por J.R.R. Tolkien que sigue la aventura de Bilbo Bolsón, un hobbit tranquilo y casero, que es arrastrado a un viaje inesperado por el mago Gandalf y un grupo de enanos. Su misión es recuperar un tesoro robado por el dragón Smaug en la Montaña Solitaria. A lo largo de su viaje, Bilbo enfrenta peligros, descubre un anillo mágico y se convierte en un héroe inesperado.",
		editorial : "Minotaurio",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/21.png?alt=media&token=8fa723af-fba7-4f38-949d-047a43af758d&_gl=1*ez43gj*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNjg4NC40NC4wLjA.",
		price : 6990,
		priceOff : 6640,
		subgenre : "Fantasía",
		title : "El Hobbit",
		type : "Ebook",
		year : "1988"
	},
	{
		id : 22,
		isbn : "9788467840551",
		author : "Frank Baum",
		category : "FANTASÍA",
		country : "Estados Unidos",
		description : "El Maravilloso Mago de Oz es una novela escrita por L. Frank Baum. La historia sigue a Dorothy, una niña de Kansas, y su perro Toto, quienes son llevados por un tornado a la tierra mágica de Oz. Para regresar a casa, Dorothy busca al Mago de Oz en la Ciudad Esmeralda, y en su viaje, se hace amiga de un espantapájaros, un hombre de hojalata y un león cobarde, cada uno en busca de algo que les falta.",
		editorial : "Anaya",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/22.png?alt=media&token=ac493144-048d-4a43-843e-068d7a54b2c9&_gl=1*1mbrtll*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzA0MS42MC4wLjA.",
		price : 11950,
		priceOff : 11352,
		subgenre : "Infantil",
		title : "El Maravilloso Mago de Oz",
		type : "Tapa Blanda",
		year : "1990"
	},
	{
		id : 23,
		isbn : "9788498414516",
		author : "Jostein Gaarder",
		category : "NUEVO INGRESO",
		country : "Noruega",
		description : "El Mundo de Sofía de Jostein Gaarder es una novela que combina la filosofía con la narrativa. La historia sigue a Sofía Amundsen, una joven que comienza a recibir misteriosas cartas que la introducen en la filosofía y la historia del pensamiento. A medida que explora las ideas de filósofos a lo largo de la historia, el libro ofrece una introducción a conceptos filosóficos clave y cuestiona la naturaleza de la realidad y la existencia.",
		editorial : "Siruela",
		genre : "Novela",
		language : "Noruego",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/23.png?alt=media&token=39634845-01ad-49ae-86f7-4e62dba316f6&_gl=1*wka4tb*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzA1Ni40NS4wLjA.",
		price : 12950,
		priceOff : 12302,
		subgenre : "Filosófica",
		title : "El Mundo de Sofía",
		type : "Tapa Blanda",
		year : "1991"
	},
	{
		id : 24,
		isbn : "9788426425737",
		author : "Umberto Eco",
		category : "CLÁSICO",
		country : "Italia",
		description : "El Nombre de la Rosa de Umberto Eco es una novela histórica ambientada en un monasterio benedictino del siglo XIV. El protagonista, Guillermo de Baskerville, un fraile franciscano y su joven aprendiz, Adso de Melk, llegan al monasterio para investigar una serie de misteriosos asesinatos. La historia combina elementos de novela policiaca con cuestiones teológicas, filosóficas y políticas de la época. A medida que avanzan en su investigación, se enfrentan a una trama de secretos, herejía y poder en la Iglesia católica medieval.",
		editorial : "Lumen",
		genre : "Novela",
		language : "Italiano",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/24.png?alt=media&token=cdca69f0-5964-4707-8113-5fd711b421d6&_gl=1*17gcgus*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzA2MS40MC4wLjA.",
		price : 19885,
		priceOff : 18862,
		subgenre : "Histórica",
		title : "El Nombre de la Rosa",
		type : "Tapa Dura",
		year : "1980"
	},
	{
		id : 25,
		isbn : "9788432242502",
		author : "Patrick Süskind",
		category : "MÁS VENDIDO",
		country : "Alemania",
		description : "El Perfume de Patrick Süskind es una novela que narra la vida de Jean-Baptiste Grenouille, un joven del siglo XVIII con un extraordinario sentido del olfato pero sin aroma propio. Obsesionado con crear el perfume perfecto, Grenouille se convierte en un asesino en busca de las esencias de las personas.",
		editorial : "Seix Barral",
		genre : "Novela",
		language : "Alemán",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/25.png?alt=media&token=5eb37281-889f-4a0f-be72-62f6af16a6c2&_gl=1*10e6rns*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzA2Ni4zNS4wLjA.",
		price : 7950,
		priceOff : 7552,
		subgenre : "Horror",
		title : "El Perfume",
		type : "Tapa Blanda",
		year : "1985"
	},
	{
		id : 26,
		isbn : "9788478887200",
		author : "Antoine de Saint-Exupéry",
		category : "FANTASÍA",
		country : "Francia",
		description : " El Principito de Antoine de Saint-Exupéry es un cuento filosófico que narra la historia de un aviador que se encuentra perdido en el desierto del Sahara y conoce a un pequeño príncipe que viene de otro planeta. A través de sus conversaciones, el Principito comparte sus experiencias y observaciones sobre la vida, la amistad y el amor.",
		editorial : "Salamanca",
		genre : "Novela",
		language : "Francés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/26.png?alt=media&token=0bac87e3-7633-4e16-a5d6-6897866dc65f&_gl=1*8ncwzh*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzMxMS41Ni4wLjA.",
		price : 14990,
		priceOff : 14240,
		subgenre : "Infatil",
		title : "El Principito",
		type : "Tapa Blanda",
		year : "1943"
	},
	{
		id : 27,
		isbn : "9788466662482",
		author : "John Katzenbach",
		category : "RECOMENDADO",
		country : "Estados Unidos",
		description : "El Psicoanalista de John Katzenbach es un thriller psicológico que sigue la historia del Dr. Starks, un psicoanalista de renombre, quien se ve acosado por un paciente anónimo que amenaza con destruir su vida y carrera si no resuelve un complicado enigma en quince días. Starks se ve obligado a descifrar el juego psicológico del paciente mientras lucha por su propia supervivencia.",
		editorial : "Ediciones B",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/27.png?alt=media&token=aa8e392d-8e71-41b6-bc22-98b7bf19e21d&_gl=1*ilpunh*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzMxOS40OC4wLjA.",
		price : 190000,
		priceOff : 180500,
		subgenre : "Misterio y/o Suspenso",
		title : "El Psicoanalista",
		type : "Tapa Dura",
		year : "2002"
	},
	{
		id : 28,
		isbn : "9788416365234",
		author : "Oscar Wilde",
		category : "MÁS VENDIDO",
		country : "Inglaterra",
		description : "El Retrato de Dorian Gray de Oscar Wilde es una novela que gira en torno a la historia de Dorian Gray, un joven apuesto que tiene un retrato pintado por un amigo. Dorian, influenciado por Lord Henry, busca la juventud eterna y comete actos de indulgencia y depravación mientras que su retrato envejece y muestra las consecuencias de sus actos.",
		editorial : "Mestas Ediciones",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/28.png?alt=media&token=dbc4f7fa-2543-4f99-9e28-2691397faa5b&_gl=1*1ojr4xm*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzMyMy40NC4wLjA.",
		price : 5950,
		priceOff : 5652,
		subgenre : "Gótica",
		title : "El Retrato de Dorian Grey",
		type : "Tapa Blanda",
		year : "1890"
	},
	{
		id : 29,
		isbn : "9788420674179",
		author : "William Golding",
		category : "MÁS VENDIDO",
		country : "Inglaterra",
		description : "El Señor de las Moscas de William Golding cuenta la historia de un grupo de niños británicos varados en una isla desierta después de un accidente aéreo. A medida que luchan por sobrevivir, los niños establecen su propia sociedad, pero la falta de supervisión adulta conduce a la violencia y la anarquía.",
		editorial : "Alianza Editorial",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/29.png?alt=media&token=df20110f-5c64-4d4a-97e0-2f0fd1e0e85e&_gl=1*7s8jg4*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzMyOC4zOS4wLjA.",
		price : 12500,
		priceOff : 11875,
		subgenre : "Aventuras",
		title : "El Señor de las Moscas",
		type : "Tapa Blanda",
		year : "1954"
	},
	{
		id : 30,
		isbn : "9788445011119",
		author : "J.R.R. Tolkien",
		category : "FANTASÍA",
		country : "Inglaterra",
		description : "El Señor de los Anillos de J.R.R. Tolkien es una épica trilogía de fantasía que sigue la odisea de Frodo Bolsón, un hobbit, para destruir un poderoso anillo maligno que amenaza con sumir a la Tierra Media en la oscuridad. Frodo forma un grupo de compañeros, incluyendo a Aragorn, Legolas y Gimli, en su viaje. Mientras tanto, otros personajes como Gandalf y Samwise Gamgee también desempeñan papeles cruciales en la lucha contra el Señor Oscuro, Sauron.",
		editorial : "Minotauro",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/30.png?alt=media&token=1198bc73-079d-4c2f-8155-e52ef999e8aa&_gl=1*cak5bh*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzMzMy4zNC4wLjA.",
		price : 65000,
		priceOff : 61750,
		subgenre : "Fantasía",
		title : "El Señor de los Anillos",
		type : "Tapa Dura",
		year : "1954"
	},
	{
		id : 31,
		isbn : "9788466346849",
		author : "Ernest Hemingway",
		category : "MÁS VENDIDO",
		country : "Estados Unidos",
		description : "El Viejo y el Mar de Ernest Hemingway es una novela corta que cuenta la historia de Santiago, un viejo pescador cubano que lucha por atrapar un gran pez espada en el mar tras 84 días sin éxito. A medida que lucha contra la naturaleza y la soledad en alta mar, se enfrenta al agotamiento físico y mental. La historia es un simbolismo de la lucha humana contra los desafíos de la vida, la resistencia frente a la adversidad y la perseverancia en la búsqueda de la dignidad.",
		editorial : "Debolsillo",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/31.png?alt=media&token=c459517e-61b9-4604-87f8-3ef091072878&_gl=1*1303j9u*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzcxMC41MC4wLjA.",
		price : 12950,
		priceOff : 12302,
		subgenre : "Aventuras",
		title : "El Viejo y el Mar",
		type : "Tapa Dura",
		year : "1951"
	},
	{
		id : 32,
		isbn : "9788484505068",
		author : "V. C. Andrews",
		category : "NUEVO INGRESO",
		country : "Estados Unidos",
		description : "Flores en el Ático de V.C. Andrews es una novela que sigue la vida de cuatro hermanos: Chris, Cathy, los gemelos Cory y Carrie. Después de la muerte de su padre, su madre, Corrine, los lleva a la mansión de sus abuelos, donde los niños son encerrados en un ático como un secreto de familia. A medida que pasan los años, los hermanos luchan por sobrevivir y mantener su unión en un entorno opresivo.",
		editorial : "Debolsillo",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/32.png?alt=media&token=5314e142-6279-45b2-8791-8e081c9fec63&_gl=1*1vrbkh*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzcxNi40NC4wLjA.",
		price : 4000,
		priceOff : 3800,
		subgenre : "Gótica",
		title : "Flores en el Ático",
		type : "Tapa Blanda",
		year : "1978"
	},
	{
		id : 33,
		isbn : "9788439730804",
		author : "Mary Shelley",
		category : "FANTASÍA",
		country : "Inglaterra",
		description : "Frankenstein de Mary Shelley es una novela que relata la historia del joven científico Victor Frankenstein, quien obsesionado con la creación de vida, da vida a un monstruo a través de experimentos científicos. Horrorizado por su creación, Victor abandona al monstruo, quien luego busca venganza al sentirse rechazado por la sociedad.",
		editorial : "Literatura Random House",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/33.png?alt=media&token=c236c399-034c-40e0-b962-a53cc7a4b54f&_gl=1*11eieet*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzcyMS4zOS4wLjA.",
		price : 21900,
		priceOff : 20805,
		subgenre : "Gótica",
		title : "Frankenstein",
		type : "Tapa Dura",
		year : "1818"
	},
	{
		id : 34,
		isbn : "9788408265320",
		author : "Lev Tolstói",
		category : "CLÁSICO",
		country : "Rusia",
		description : "Guerra y Paz de León Tolstói es una novela épica que narra la historia de cinco familias aristocráticas durante la invasión napoleónica de Rusia en el siglo XIX. La obra se centra en los personajes de Pierre Bezukhov, Andrei Bolkonsky y Natasha Rostova, quienes experimentan el amor, la guerra y la transformación personal en medio de los eventos históricos.",
		editorial : "Planeta",
		genre : "Novela",
		language : "Ruso",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/34.png?alt=media&token=2b5df637-5564-4272-af5c-78818f823178&_gl=1*14782ml*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzcyNi4zNC4wLjA.",
		price : 34950,
		priceOff : 33202,
		subgenre : "Histórica",
		title : "Guerra y Paz",
		type : "Tapa Dura",
		year : "1865"
	},
	{
		id : 35,
		isbn : "9788478884452",
		author : "J. K. Rowling",
		category : "FANTASÍA",
		country : "Inglaterra",
		description : "Harry Potter y la Piedra Filosofal de J.K. Rowling es el primer libro de la famosa serie. Narra la historia de Harry Potter, un huérfano que descubre que es un mago y asiste a la escuela de magia Hogwarts. Allí, conoce a Ron Weasley y Hermione Granger y descubre la existencia de la Piedra Filosofal, un objeto que otorga inmortalidad. Harry, junto con sus amigos, se embarca en una aventura para evitar que la piedra caiga en las manos equivocadas.",
		editorial : "Salamandra",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/35.png?alt=media&token=64da1966-c8dd-4172-be48-34081924e8fd&_gl=1*pe5by*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxNzczMS4yOS4wLjA.",
		price : 15990,
		priceOff : 15190,
		subgenre : "Fantasía",
		title : "Harry Potter y la Piedra Filosofal",
		type : "Tapa Dura",
		year : "1997"
	},
	{
		id : 36,
		isbn : "9788484287360",
		author : "Charles Dickens",
		category : "CLÁSICO",
		country : "Inglaterra",
		description : "La Historia de Dos Ciudades de Charles Dickens se desarrolla en Londres y París durante la Revolución Francesa. La novela sigue a varios personajes, incluido Charles Darnay, quien es acusado injustamente de espionaje, y Sydney Carton, un abogado alcohólico y desilusionado. La trama se centra en la persecución de Darnay y la transformación de Carton, quien encuentra redención al sacrificar su vida por otro.",
		editorial : "Alba Editorial",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/36.png?alt=media&token=8475e849-2c91-4585-be03-51c2bead7750&_gl=1*1ga1685*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODA5MC4zOC4wLjA.",
		price : 9990,
		priceOff : 9490,
		subgenre : "Histórica",
		title : "Historia de Dos Ciudades",
		type : "Ebook",
		year : "1859"
	},
	{
		id : 37,
		isbn : "9788489846869",
		author : "Charlotte Brontë",
		category : "CLÁSICO",
		country : "Inglaterra",
		description : "Jane Eyre de Charlotte Brontë es una novela que cuenta la historia de la huérfana Jane Eyre, quien crece en un hogar abusivo y se convierte en institutriz en Thornfield Hall, donde trabaja para el enigmático Sr. Rochester. Jane y Rochester desarrollan una relación complicada que se ve obstaculizada por un oscuro secreto en la mansión.",
		editorial : "Alba Editorial",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/37.png?alt=media&token=e0d809a7-04ce-44a0-b7f8-4f0ee091bd64&_gl=1*i7baij*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODEwMC4yOC4wLjA.",
		price : 32000,
		priceOff : 30400,
		subgenre : "Gótica",
		title : "Jane Eyre",
		type : "Tapa Dura",
		year : "1847"
	},
	{
		id : 38,
		isbn : "9788401032424",
		author : "George R. R. Martin",
		category : "RECOMENDADO",
		country : "Estados Unidos",
		description : "Juego de Tronos de George R.R. Martin es el primer libro de la serie Canción de Hielo y Fuego. La trama se desarrolla en el ficticio continente de Poniente y sigue a varias casas nobles mientras compiten por el Trono de Hierro de los Siete Reinos. La historia está llena de traición, intriga política y elementos de fantasía, como dragones y caminantes blancos.",
		editorial : "Plaza & Janes Editores",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/38.png?alt=media&token=d852bc22-122e-4e84-a120-84024fb8b3c2&_gl=1*1o9u90g*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODEwNy4yMS4wLjA.",
		price : 27900,
		priceOff : 26505,
		subgenre : "Fantasía",
		title : "Juego de Tronos",
		type : "Tapa Dura",
		year : "1996"
	},
	{
		id : 39,
		isbn : "9789877672329",
		author : "Franz Kafka",
		category : "RECOMENDADO",
		country : "Alemania",
		description : "La Metamorfosis de Franz Kafka narra la historia de Gregor Samsa, un vendedor que un día despierta transformado en un insecto gigante. Aislado en su habitación, enfrenta la alienación de su familia y la sociedad a medida que su condición empeora. La transformación de Gregor es tanto física como simbólica, y la historia refleja la sensación de impotencia y aislamiento en un mundo que lo rechaza.",
		editorial : "Planeta",
		genre : "Novela",
		language : "Alemán",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/39.png?alt=media&token=f4464a1c-673a-4131-b8db-aa1d2fbc4c8b&_gl=1*4h3gat*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODExMy4xNS4wLjA.",
		price : 9990,
		priceOff : 9490,
		subgenre : "Existencial",
		title : "La Metamorfosis",
		type : "Ebook",
		year : "1951"
	},
	{
		id : 40,
		isbn : "9788417127916",
		author : "Julio Verne",
		category : "FANTASÍA",
		country : "Francia",
		description : "La Vuelta al Mundo en 80 Días de Julio Verne cuenta la historia de Phileas Fogg, un caballero inglés que hace una apuesta para dar la vuelta al mundo en 80 días, una hazaña aparentemente imposible en la década de 1870. Acompañado por su fiel criado Passepartout, Fogg se embarca en un viaje lleno de desafíos, aventuras y obstáculos inesperados, incluyendo perseguidores y situaciones peligrosas.",
		editorial : "Gribaudo Editorial",
		genre : "Novela",
		language : "Francés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/40.png?alt=media&token=1421643c-fda0-460c-a965-c53cc98b93e5&_gl=1*19ev0lj*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODEyMC44LjAuMA..",
		price : 15900,
		priceOff : 15105,
		subgenre : "Aventuras",
		title : "La Vuelta al Mundo en 80 Días",
		type : "Tapa Dura",
		year : "1872"
	},
	{
		id : 41,
		isbn : "9788413141282",
		author : "Margaret Mitchell",
		category : "CLÁSICO",
		country : "Estados Unidos",
		description : "Lo Que el Viento se Llevó de Margaret Mitchell se desarrolla durante la Guerra Civil estadounidense y sigue a Scarlett O'Hara, una joven sureña mimada y testaruda. La historia narra su vida, amores y desafíos en el contexto de la guerra y la reconstrucción del Sur. Scarlett es un personaje complejo que lucha por sobrevivir y adaptarse a las circunstancias cambiantes, mientras que su amor no correspondido por Ashley Wilkes y su complicada relación con Rhett Butler son elementos centrales de la trama.",
		editorial : "B de Bolsillo",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/41.png?alt=media&token=931dfb48-ff42-4a42-b0a4-e0b6f60ab0f8&_gl=1*w1isjh*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODQ5My41NC4wLjA.",
		price : 14950,
		priceOff : 14202,
		subgenre : "Histórica",
		title : "Lo Que el Viento se Llevó",
		type : "Tapa Blanda",
		year : "1939"
	},
	{
		id : 42,
		isbn : "9788433960177",
		author : "Vladimir Nabokov",
		category : "MÁS VENDIDO",
		country : "Estados Unidos",
		description : "Lolita de Vladimir Nabokov narra la obsesión enfermiza del narrador, Humbert, por una joven llamada Dolores Haze, a quien apoda Lolita. Humbert se convierte en el padrastro de Lolita y comete abuso sexual en su relación con ella. La novela está escrita desde la perspectiva de Humbert, lo que lleva al lector a cuestionar la moralidad y la justificación de sus acciones.",
		editorial : "Anagrama",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/42.png?alt=media&token=d7297b30-0ff1-4afd-b2e4-b4388457da4b&_gl=1*1u6659p*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODUyMC4yNy4wLjA.",
		price : 13900,
		priceOff : 13205,
		subgenre : "Erótica",
		title : "Lolita",
		type : "Tapa Blanda",
		year : "1955"
	},
	{
		id : 43,
		isbn : "9782377932436",
		author : "Victor Hugo",
		category : "CLÁSICO",
		country : "Francia",
		description : "Los Miserables de Victor Hugo es una novela ambientada en la Francia del siglo XIX que narra las vidas entrelazadas de varios personajes, incluyendo a Jean Valjean, un exconvicto que busca redimirse; Javert, un inflexible inspector de policía que lo persigue; y Cosette, una joven rescatada de la miseria. La trama abarca décadas y explora temas de justicia, redención, amor y la lucha contra la pobreza y la opresión.",
		editorial : "Autor-Editor",
		genre : "Novela",
		language : "Francés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/43.png?alt=media&token=0c088a74-51b6-40c3-8d17-27243878fa28&_gl=1*1vjvloe*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODUxNC4zMy4wLjA.",
		price : 490,
		priceOff : 465,
		subgenre : "Histórica",
		title : "Los Miserables",
		type : "Ebook",
		year : "1862"
	},
	{
		id : 44,
		isbn : "9788417247201",
		author : "Harper Lee",
		category : "CLÁSICO",
		country : "Estados Unidos",
		description : "Matar a un Ruiseñor de Harper Lee se desarrolla en la década de 1930 en el sur de Estados Unidos y sigue a Scout Finch, una niña que observa a su padre, Atticus Finch, defender a un hombre negro acusado injustamente de violar a una mujer blanca. A través de los ojos de Scout, la obra ofrece una mirada conmovedora a la lucha por los derechos civiles y la inocencia perdida en una comunidad del sur.",
		editorial : "Random Comics",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/44.png?alt=media&token=12c84251-d65f-4fcd-8979-82355e389502&_gl=1*m4ubo5*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NzUzNzg0OC41LjEuMTY5NzUzNzk3OC4zMC4wLjA.",
		price : 24900,
		priceOff : 23655,
		subgenre : "Aprendizaje",
		title : "Matar a un Ruiseñor",
		type : "Tapa Dura",
		year : "1960"
	},
	{
		id : 45,
		isbn : "9788492549290",
		author : "Herman Melville",
		category : "FANTASÍA",
		country : "Estados Unidos",
		description : "Moby Dick de Herman Melville es una novela épica que sigue al narrador, Ismael, y su obsesiva búsqueda de venganza contra el gran cachalote blanco, Moby Dick, bajo el liderazgo del obsesivo capitán Ahab. La historia se desarrolla en un barco ballenero llamado el Pequod y se convierte en una odisea en alta mar que explora temas de obsesión, destino y la lucha entre el hombre y la naturaleza. La novela también ofrece observaciones profundas sobre la relación entre el individuo y el cosmos.",
		editorial : "Labutxaca",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/45.png?alt=media&token=473163b3-b5ac-41f3-bd55-0f1521960c28&_gl=1*1cp5qro*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODUwMS40Ni4wLjA.",
		price : 12950,
		priceOff : 12302,
		subgenre : "Aventuras",
		title : "Moby Dick",
		type : "Tapa Blanda",
		year : "1851"
	},
	{
		id : 46,
		isbn : "9788424939076",
		author : "Homero",
		category : "MÁS VENDIDO",
		country : "Grecia",
		description : "La Odisea de Homero es un poema épico que sigue las aventuras de Odiseo (Ulises) en su viaje de regreso a casa después de la Guerra de Troya. Durante su ausencia, su esposa Penélope lucha contra los pretendientes que la acosan, mientras que Odiseo enfrenta desafíos mortales, como la visita a la isla de los cíclopes y la trampa de la sirena Caribdis.",
		editorial : "Gredos",
		genre : "Poema Épico",
		language : "Griego Antiguo",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/46.png?alt=media&token=09f58e4a-1ef4-41d1-ac03-17c152b7e9ad&_gl=1*3jfwg7*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODk3NC4yNy4wLjA.",
		price : 20000,
		priceOff : 19000,
		subgenre : "Epopeya",
		title : "Odisea",
		type : "Tapa Dura",
		year : "VIII A.C."
	},
	{
		id : 47,
		isbn : "9788467070835",
		author : "Jane Austen",
		category : "RECOMENDADO",
		country : "Inglaterra",
		description : "Orgullo y Prejuicio de Jane Austen se centra en la vida de Elizabeth Bennet, una joven inteligente y vivaz, y su relación con el arrogante pero apuesto Mr. Darcy. La novela se desarrolla en la Inglaterra rural del siglo XIX y aborda temas de clase social, matrimonio y el papel de la mujer en la sociedad. A medida que Elizabeth y Darcy superan sus prejuicios y orgullos, descubren el amor verdadero.",
		editorial : "Espasa Libros",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/47.png?alt=media&token=08190c23-3d6d-410d-8e8c-97b38d5769bc&_gl=1*enzlqm*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODk2OS4zMi4wLjA.",
		price : 15950,
		priceOff : 15152,
		subgenre : "Romántica",
		title : "Orgullo y Prejuicio",
		type : "Tapa Dura",
		year : "1813"
	},
	{
		id : 48,
		isbn : "9788420414706",
		author : "Julio Cortázar",
		category : "NUEVO INGRESO",
		country : "Argentina",
		description : "Rayuela de Julio Cortázar es una novela experimental que desafía las convenciones narrativas tradicionales. La historia sigue a Horacio Oliveira, un argentino en París, y se presenta en un formato no lineal, lo que permite al lector elegir diferentes formas de leerla. La trama explora la búsqueda de sentido y la identidad en un mundo caótico, y mezcla elementos de la realidad y la ficción.",
		editorial : "Alfaguara",
		genre : "Novela",
		language : "Español",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/48.png?alt=media&token=fb8a424d-88ce-4e01-85a8-0b4b9bfb75d2&_gl=1*4lpqo2*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxOTIxMS42MC4wLjA.",
		price : 21900,
		priceOff : 20805,
		subgenre : "Antinovela",
		title : "Rayuela",
		type : "Tapa Blanda",
		year : "1963"
	},
	{
		id : 49,
		isbn : "cdlap00011573",
		author : "William Shakespeare",
		category : "CLÁSICO",
		country : "Inglaterra",
		description : "Romeo y Julieta de William Shakespeare es una tragedia que narra el amor prohibido entre Romeo Montesco y Julieta Capuleto, dos jóvenes de familias enemistadas en Verona, Italia. Su amor los lleva a casarse en secreto, pero una serie de malentendidos y fatalidades desencadenan una serie de trágicos eventos que culminan en la muerte de los amantes.",
		editorial : "Autor Editor",
		genre : "Novela",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/49.png?alt=media&token=e84e525b-d468-4774-840d-552ffe2a6256&_gl=1*w8usje*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODk1Ny40NC4wLjA.",
		price : 2990,
		priceOff : 2840,
		subgenre : "Tragedia",
		title : "Romeo y Julieta",
		type : "Ebook",
		year : "1597"
	},
	{
		id : 50,
		isbn : "9788420671727",
		author : "Virginia Woolf",
		category : "MÁS VENDIDO",
		country : "Inglaterra",
		description : "Una Habitación Propia de Virginia Woolf es un ensayo que aborda la cuestión de la mujer y la escritura en la sociedad patriarcal del siglo XX. Woolf argumenta que para que las mujeres escriban con éxito necesitan independencia económica y un espacio propio. Ella explora la historia de la opresión de las mujeres, su exclusión de la educación y la literatura, y cómo esto ha afectado su capacidad de expresión.",
		editorial : "Alianza Editorial",
		genre : "Ensayo",
		language : "Inglés",
		photo : "https://firebasestorage.googleapis.com/v0/b/libreriacacp.appspot.com/o/50.png?alt=media&token=bf49ae18-7d92-453a-a781-00d065f748e0&_gl=1*fc4c1o*_ga*OTc4NDM2OTgxLjE2OTY1MDE0MzA.*_ga_CW55HF8NVT*MTY5NjUxNjc5MS4yLjEuMTY5NjUxODk1MC41MS4wLjA.",
		price : 12500,
		priceOff : 11875,
		subgenre : "Feminismo",
		title : "Una Habitación Propia",
		type : "Tapa Blanda",
		year : "1929"
	}
]